### ISSUE TITLE
[Feature Request] Fill ontology gap via SWATE

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#147]
**Is your feature request related to a problem? Please describe.**

More an idea inspired by the ontology workshop today. 
Can we implement an ontology request form similar to https://submit.rtbbase.org in SWATE to link to the NFDI4PSO ontology and allow direct user / data steward input from within SWATE? 

Alternatively, I guess missing terms will be captured by user SWATE sheets with free-text building blocks, and then data stewards import and curate the terms.

**Comment by Freymaurer** [comment]
I really like the idea and gave it some thoughts since you posted this issue. 

Currently users need a github account for a lot of feedback and interaction parts for Swate. This is obviously not good, So i think an OAuth authorisation via GitHub for users with an GitHub Account, and a Swate-Feedback "Bot" (A special user account linked to the Swate backend), which can post feedback  for users via a Feedback form in Swate.

**Comment by Brilator** [comment]
Not highest priority for user feedback (for which I would link it to authentication through hub / elixir AAI). But could already help stewards during templating. 

That said, I also have a few ideas for template / template database improval. But let's discuss this in a few weeks - other things are currently more urgent.

**Comment by Freymaurer** [comment]
We now have a helpdesk, which everyone without account can use. This should tackle the issue on the Swate side of things ;)
