### ISSUE TITLE
Swate window in excel is empty after installation

### ISSUE THREAD

**Issue by christinerempfer** [nfdi4plants/Swate#148]
Hello,
we have an issue with setting up Swate on the computers in our lab (Windows 10 enterprise with Office 2016). The installation of Swate according to the instructions using the release archive runs through without error messages, however the window in Excel where the Swate plugin should be displayed is empty (see screenshot below).  Is there a possibility for us to check what causes this issue to get some hints how we can solve it?  

![Screenshot_empty_window](https://user-images.githubusercontent.com/25619067/123845432-775ba480-d914-11eb-9d9d-3e9893b0b98f.png)

**Comment by Freymaurer** [comment]
Hello, thanks for your message. I will gladly try and solve this issue with you.

Can you tell how exactly you used the installation? This part can be a bit tricky, but we hope to make Swate accessible via the store soon. 😄

**Comment by christinerempfer** [comment]
thanks for helping with this issue. The installation was done according to the instruction. First it was made sure that Node.js is installed. Next the Swate script in the latest release archive was executed. We tried both running it without administrator rights and with administrator rights also starting it from the command line but nothing solved the issue.  Below is the output on the command window before  Excel with the empty Swate window is started. 
![Screenshot_execution](https://user-images.githubusercontent.com/25619067/123951520-2d6ecf00-d9a5-11eb-8dec-b7c5b6b841db.png)

**Comment by Freymaurer** [comment]
Okay, this could get a bit difficult, as i do not have access to a office 2016 version. Could you try to set up a free [office online ](https://uk.pcmag.com/office-suites/90356/how-to-use-microsoft-office-for-free-on-the-web)? There you can easily insert the add-in and test it.

![image](https://user-images.githubusercontent.com/39732517/123954797-18943a80-d9a9-11eb-8807-6cb6c4f937f6.png)
Upload the manifest.xml in the swate folder.

**Comment by zwuckl** [comment]
Hi Kevin,

thanks for your responses so far. We've experienced the issue Christine described on a bunch of different machines running a combination of Windows 7 or 10 and Office 2016 Professional and a Mac running MacOS 11.4 with Office 2016 Standard. Although we followed the instructions, including a fresh install of node.js LTS, we only get this empty SWATE as in Christine's screenshot.

Unfortunately, switching to the online version of Office is not a feasible option for us, since we're trying to establish a model ARC workflow in our lab and would like to stick with the software that people are used to. Also on the exact same systems we ran SWATE successfully at some point last year as part of our first proof of concept evaluation.

Since we are no experts on Office add-in development: is there any way to enable local logging so that we can check what's going on/wrong during the installation and startup of Excel? Does it trigger any Windows events that can be checked?

Thanks
Nico

**Comment by Freymaurer** [comment]
Thanks for the feedback, today i and @omaus worked on a new Swate installer. Please check if it fixes your problem 👍 

[New Installer](https://github.com/omaus/Swate_Install#swate-installer)

If not, you can maybe check here:

![image](https://user-images.githubusercontent.com/39732517/124158971-dc410700-da9a-11eb-8660-81b08f1da6be.png)

Please check both "Security info" and "Attach debugger". We can also arrange a meeting to try and solve the problem via screen sharing.

**Comment by christinerempfer** [comment]
Thanks for the new Swate installer. We have tested it, but it did not solve the issue with the empty Swate window.  The options "Security info" and "Attach debugger" are not present in this case. Hence, we would like to arrange a date with you to solve the problem via screen sharing.

**Comment by Freymaurer** [comment]
Could you please additionally give me a screenshot of the installer outputs? We Propably have to get an office 2016 version before we arrange that meeting, so we can test some things beforehand.

**Comment by christinerempfer** [comment]
Here is a screenshot of the installer outputs. We did not unistall the previously installed Swate version before executing the new installer. 
![screenshot_new_installer](https://user-images.githubusercontent.com/25619067/124493184-a0b57e00-ddb5-11eb-9db7-76e3534510d1.png)

**Comment by omaus** [comment]
From here it looks like incompatibilities of Swate with Excel 2016 since everything installed successfully and the connection to the SwateDatabase works flawlessly as well.
Could you please try if Swate works in [Excel online](https://www.office.com/launch/excel?ui=de-DE&rs=DE&auth=1)? (Installing guide can be found [here](https://github.com/nfdi4plants/Swate#excel-online))
If it works there, we can be 100 % sure about the problem lying in Excel 2016 version.

You maybe need a Microsoft account for accessing Excel online.

**Comment by omaus** [comment]
Regarding an online meeting: Are you part of the Slack Team for DataPLANT? If that's the case we can talk about this in more detail there.

**Comment by christinerempfer** [comment]
Swate works fine in Excel online. I don't think we are part of the Slack Team for DataPLANT. Can we be added?
