### ISSUE TITLE
[BUG] Wrong "Created" date for templates 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#260]
**Describe the bug**
In the templates search menu, all templates are shown as "Created:" with today's date.

**Comment by Brilator** [comment]
not sure if swate or swobup bug @Zerskk

**Comment by Freymaurer** [comment]
This is an issue we have with database persistancy. Due to our service-on-demand approach the database can be build/rebuilt with ease but it is difficult for us to persist information between these database states. 

You might also notice that all "Times used" counter where reset to 0.

Me and Marcel are already discussing solutions to this issue, but none of them are very clean. So this was kinda pushed to the backlog.

**Comment by Freymaurer** [comment]
Will add this as Swobup issues and close this here.
