### ISSUE TITLE
[BUG] SWATE online does not fill in Unit columns

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/Swate#300]
I noticed that when building blocks are filled in SWATE online, the Unit column is always annotated as "user-specific" even if a unit with an existing ontology is picked.

[SWATE [v0.6.2] in Excel Online]

**Comment by Freymaurer** [comment]
> Unfortunately I am having trouble loading Swate right now so I can't look up the unit source refs and accession numbers, but other examples were:

Yes sorry we are currently doing maintenance on all our major services, you can see the current status here: https://status.nfdi4plants.org/status/dataplant

About your problem, whatever it was it is already fixed in the next Swate version 🎉 

![image](https://user-images.githubusercontent.com/39732517/228872998-bb265dd2-0fc7-4bff-8860-5742719a70fe.png)
