### ISSUE TITLE
[BUG] AddIn blank in Excel

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/Swate#302]
Issue recieved via help desk mail on 24.03.2023

Dear DataPlant Team,
After clearing the Add-In cache and installing Swate following the given instructions on your website, the Add-In does not function, only displaying a blank square (Desktop Installation v0.6.2 on Windows 10 Enterprise N, Microsoft Office prof.plus 2019 - Excel version 1808). We replicated this issue on a second, analogous system and would be glad if you could help us with this issue.
Yours faithfully,

The user requested feedback to: [removed]

**OS and framework information (please complete the following information):**
 - Windows 10 Enterprise N,
 - Microsoft Office prof.plus 2019 - Excel version 1808

**Describe the bug**
After clearing the Add-In cache and installing Swate following the given instructions on your website, the Add-In does not function, only displaying a blank square

**Comment by Freymaurer** [comment]
Hello thanks for the feedback! Sadly, due to changes in different environments we don't have control over Swate cannot run on any Excel 2019 version anymore.

If possible use the [free web version of Excel](https://www.office.com/launch/excel?ui=en-US&rs=GB&auth=1) or try the new [standalone version of Swate](https://swate-alpha.nfdi4plants.org) (only a alpha version at the moment).

Please let us know if those options are not possible for you and why 😃
