### ISSUE TITLE
[BUG] Dead links to DPBO

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#321]
The links of ontology terms from DPBO (https://github.com/nfdi4plants/nfdi4plants_ontology) are obviously non-existent. 
This might be frustrating for users. 

Not sure, wether it's possible to auto-generate a link to the respective ID in the [dpbo.obo](https://github.com/nfdi4plants/nfdi4plants_ontology/blob/main/dpbo.obo). 

Alternatively, DPBO terms could just link to the ontology gh repo or remove the auto-generated links.

Discussed with @shiltemann

**Comment by Freymaurer** [comment]
You are right, maybe our ontology team can set something up so we can generate purl links from our ontology or redirect them to the repository. Until then a quick-and-dirty solution would be for me in Swate to redirect als DPBO:xxxxxx accessions to the repository.

**Comment by Hannah-Doerpholz** [comment]
So, as we just had this discussion, since I have already set up purls for the ARC container ontology I could try to do that for dpbo. Currently all dead dpbo purls include the /obo/ domain which does not belong to me. Since the file is an obo file it seems like the IRI cannot be changed for this purpose (it does work for owl files though). @Freymaurer Where is Swate taking the links to the dpbo terms from? Can this be changed to custom links?

**Comment by Freymaurer** [comment]
Yes, it is currently a hard-coded format string. But the development of Swate is currently stopped in favor of ARCitect. Therefore, this problem should be solved in general and not at Swate level.

**Comment by UrsulaE** [comment]
Even if linking all terms to the right place would be too troublesome at the moment, a link to the file dpbo.obo would be very helpful in the meantime.

**Comment by Hannah-Doerpholz** [comment]
We have discussed how to deal with the dead DPBO links and will fix it after the current pause in the Swate development. We also noticed that the MS links are currently dead as well and have contacted the developers (although it might be an issue for the OBO Foundry)

**Comment by Freymaurer** [comment]
Will close here, handled in #324
