### ISSUE TITLE
[Feature Request] FilePicker should allow to pick folder files

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Swate#383]
**Is your feature request related to a problem? Please describe.**
Some MS vendor formats (e.g. those of Bruker) report the run data as a folder instead of a single file. For this it would be great to have the filepicker be able to also select single or multiple folders. 

**Describe the solution you'd like**
Similar behaviour to picking files for folders

**Comment by ZimmerD** [comment]
Sorry for not providing a better description. I had the latter case in mind, specifically referencing the folder.

**Comment by Freymaurer** [comment]
This is very difficult to implement, as websites do not have access to path. So at best i could return the name of the folder. But a quick search showed even this to be rather difficult.

Let me know what exactly you would need with an example and which alternatives you would be okay with. Thanks in advance!

**Comment by ZimmerD** [comment]
I think the name of the folder would be sufficient. I think a function like this would be needed since e.g. Bruker does not create a single file as an output for a MS run but rather a folder with many files. 

The resulting data would look like this:
![image](https://github.com/nfdi4plants/Swate/assets/17741807/004e1f4c-47ca-4e63-a4b8-773231e99226)

This is how I like to reference it in the workbook sheet:
![image](https://github.com/nfdi4plants/Swate/assets/17741807/e00400f3-14df-4044-903d-ee3db0cd1c63)

For the user a workaround could be to simply zip the folder. However this is rather impractical since most tools only accept it unzipped.

**Comment by Freymaurer** [comment]
So here is the thing. There is an API to upload folders instead of files, but.. This API MUST upload the files inside the folder and then i can get the folder name from the relative paths of these files. For me on opera this process triggered a warning, asking me if i really want to upload all these files. In addition i think the file size can get quite large for something as simple as a folder name.

@ZimmerD of course you can give me additional input on this topic, but currently i think this is simply not possible to do in Swate. But(!) Swate in ARCitect should be able to solve this issue with Electron features!

**Comment by Freymaurer** [comment]
Added Relative paths and folder pick option for ARCitect ✨ Thanks to @JonasLukasczyk for the ARCitect side help
