### ISSUE TITLE
[Feature Request] Sort ontology term search results by relevance/obsolete status

### ISSUE THREAD

**Issue by shiltemann** [nfdi4plants/Swate#492]
### Is your feature request related to a problem?

When searching ontology terms in ARCitect, it would be helpful if the most relevant terms (such as "Related Terms") are shown on top, and obsolote terms either hidden or sorted to the bottom (and if shown, preferably somehow made obvious without expanding when a term is obsolete)

### Describe the solution you would like!

Example, searching for "single" in the library strand column, I would expect the result marked as a "Related term" to show up on top. Furthermore, the 3rd result in this screenshot is marked as obsolete, I would expect these to be at the bottom (or just hidden altogether, unless there is some use case for including them that I am not aware of?).

![image](https://github.com/user-attachments/assets/c466abe9-96de-4414-ac01-2e42764bd28b)

### Additional context!

nitpick: the "related terms" icon is what most people will know as the "share" icon, perhaps a star is a better icon?

### Host

Applies to All

### Host Details

ARCitect v0.0.40
Ubuntu 22.04

**Comment by Freymaurer** [comment]
Hey, thanks for the feedback!

> Example, searching for "single" in the library strand column, I would expect the result marked as a "Related term" to show up on top.

The term search actually runs 2 different search queries: One only querying name and the other for parent-child search. The latter is way more performance heavy and depending on the exact terms and their respective ontology may even through, because it takes more than 3s. 
We run both queries, name-only query returns first. We build the search results and show the user. In the meantime we still await parent-child and when (if) the results arrive, we update the existing result list with the icon.

Why update icon and not reorder? Because changing the UI this drastically makes the user click the wrong items (think old google ads). I do think it is better to keep the UI static after showing the first results and not reordering.

> Furthermore, the 3rd result in this screenshot is marked as obsolete, I would expect these to be at the bottom (or just hidden altogether, unless there is some use case for including them that I am not aware of?).

Partly the same reasoning as for the first part. But it should absolutly display obsolete more prominent!

> nitpick: the "related terms" icon is what most people will know as the "share" icon, perhaps a star is a better icon?

I see, what do you think of this one? https://fontawesome.com/icons/diagram-project?f=classic&s=solid

I fear that a star icon could be taken too evaluatively.

**Comment by shiltemann** [comment]
Hi @Freymaurer Thanks for the detailed response!

Ah, so you mean the results might jump around after initial load? Yes, that would be problematic, thanks for explaining :+1: 

> I fear that a star icon could be taken too evaluatively.

Ah ok, I assumed we wanted to encourage selecting the related terms so a bit of evaluativeness in the form of a star or checkmark would be called for. The icon you suggest makes sense to indicate "related" or "parent-child", just not 100% sure an end user has that mental model (of terms being related to the column definition), but also don't know what icon might be better there then, so sounds good to me :)

**Comment by Freymaurer** [comment]
> Ah ok, I assumed we wanted to encourage selecting the related terms so a bit of evaluativeness in the form of a star or checkmark would be called for. 

We want to offer the user more information without valuing one more than the other. Should any user not find the term they are looking for in our database they can also just type it as free text without feeling bad. This is fully supported and intended by our data annotation framework 🙂

**Comment by Freymaurer** [comment]
Hey! I updated the icon for related term and obsolete terms will now show a [link slash](https://fontawesome.com/icons/link-slash?f=classic&s=solid) icon in red at the same position!

In addition i noticed that you were able to find NFDI4PSO terms in the database which should not be included so i'll look into that as well!

**Comment by shiltemann** [comment]
Awesome, thanks @Freymaurer  :+1:
