### ISSUE TITLE
[BUG] Swate table jumps during scrolling

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/Swate#504]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
 - ARCitect v0.0.40

**Describe the bug**
- I currently have 67 rows in one of my Swate sheets
- when I scroll up to mark multiple cells in one column, the sheet jumps along the x-axis (check the video below)
- this is really irritating, especially when I want to copy larger parts of one column, or when I want to compare values of the same column
- it also makes me lose count more easily of my current row that I wanted to edit

https://github.com/user-attachments/assets/b798d707-9045-408f-a461-1e6200cdbf56

**Comment by Freymaurer** [comment]
I know why this is happening. The new lazy load table does not render all cells at every time. Most likely one of the upper cells to the left has a lot of content different to the cells below. Then you scroll up, the cell gets loaded and because it is wider than the cells below it pushes the other columns to the right.

This issue is not easy to fix. I'll propably add a fixed width to the cells similiar to how Excel does it

**Comment by Hannah-Doerpholz** [comment]
Yes, on the left side I always have protocol descriptions, and some of them are very long, while others are much shorter. I'll try putting those columns all the way to the right and see if that helps me while I'm working on the ARC for the moment. Thank you for the hint!

**Comment by Freymaurer** [comment]
Okay! I applied some fixes hopefully. I tried replicating excel logic for this now. width is iniatially set to 300, but can be resized between 200-600 (this manual resize will propagate through lazy load table). Large cell content will be hidden, but can be seen hovering over the cell. Cell editing should be unchanged. 

Let me know what you think/how it feels.

Will be live with the next release (After PR #503 )
