### ISSUE TITLE
[Bug]: Change column header to "Characteristics" didn't work

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/Swate#521]
### Contact Details

sabrina.zander@hhu.de

### What happened?

I want to update a existing column from a "Parameter" to a "Characteristic". This didn't work. You can select "Characteristic" but the column header is not updated. If you want to change the column to any other term it works. 
Maybe there is a bug in the selection because "Characteristic" is the first term in the selection. 

### Host

Standalone

### Host Details

Standalone (Browser Google Chrome) 

### Swate version

I assume v.1.00 beta 07

**Comment by Freymaurer** [comment]
Hello thanks for the feedback, i am currently still on vacation. Will look into this as soon as i get back.

For now you can fix this by editing the xlsx file by hand. I am sorry for the inconvinience!

**Comment by SabrinaZander** [comment]
No problem, I only wanted to let you know.

**Comment by Freymaurer** [comment]
I checked it and i think the issue is with `characteristic` being the default. The component checks applies updates on selection change. By clicking on `characteristic` it does not change as it is selected by default. If i click anything else and then `characteristic` it works. Can you verify this behavior on your side @SabrinaZander ? If yes, i will start working on a fix

**Comment by SabrinaZander** [comment]
Yes, exactly

**Comment by Freymaurer** [comment]
Done! will be live with the next release!
