### ISSUE TITLE
[Feature Request] Version hard to find. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#81]
**Is your feature request related to a problem? Please describe.**
Not sure, which version of SWATE I'm currently using (i.e. on different Desktops + web) and cannot find version in the manifest.xml nor within the add-in. This makes it hard to check whether issues may be related to different versions.  

**Describe the solution you'd like**
a) Rename archive behind swate.zip -> e.g. PreRelease_Swate-0.1.3
b) Add version to info icon (top right) within the add-in.

**Comment by Freymaurer** [comment]
How it works: 

- The swate.zip is unchanged since the very first release pack.
- What the add in does is it connects excel with a webpage that can also be accessed without excel (https://swate.denbi.uni-tuebingen.de/).
- The webpage can interact with excel and the current version of Swate depends on the version we run on the server.
- The current version of Swate up and running can be seen here:
![image](https://user-images.githubusercontent.com/39732517/102596869-1740a600-411a-11eb-8b9c-2d49d3b73d81.png)

**Comment by Brilator** [comment]
Ah, right. Totally makes sense since SWATE isn't working as local standalone anyways. Thanks for clarification.
