### ISSUE TITLE
[BUG] SWATE annotation lost (from column headers)

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#87]
**Describe the bug**
SWATE annotation is lost after insertion of a building block. 

**To Reproduce**
1. Insert any annotation block
2. Wait a few seconds
3. See error: Actual column header (e.g. parameter, characteristics) stays; the two additional headers (ontology ref) are renamed to "Column XY"

**Screen recording**
https://user-images.githubusercontent.com/16229676/104340067-9a2a0600-54f8-11eb-8e65-c8145077587e.mp4

**OS and framework information (please complete the following information):**
 - MS Excel Online

**Comment by Freymaurer** [comment]
Thank you for your submission. I was able to replicate this bug in excel online and will look into it!

it seems that this issue is related to the reference column input assistance. You can deactivate the feature after creating a table by clicking on the button shown below.
![image](https://user-images.githubusercontent.com/39732517/104431273-ff790800-5587-11eb-948d-0e0f441e7537.png)
![image](https://user-images.githubusercontent.com/39732517/104431354-13bd0500-5588-11eb-8e23-d0061f55897d.png)

**Comment by Freymaurer** [comment]
Apparently it is currently not possible to correctly deactivate onChange events in excel online. What this means is, that the reference column input assist will falsely interfer with other Swate functions as we cannot set it to stand by during these operations.

Therefore the input assistant feature will be removed and it's functioniality is added to "Update Reference Columns"

![image](https://user-images.githubusercontent.com/39732517/105945599-e0897400-6065-11eb-9cbf-d96abe0d6c8d.png)

This change will be live in version 0.2.1
