### ISSUE TITLE
[Feature Request] Reset unit search 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate#92]
**Is your feature request related to a problem? Please describe.**
After addition of an anno building block, that hast a unit the selected term for the unit sticks in the search field for "This Chara/Para/Factor has a unit". 

**Describe the solution you'd like**
Reset unit term after building block has been added to anno table or when searching for a new term (sometimes it might actually be useful to reuse a unit directly - e.g. temp at night, temp at day). 

**Describe alternatives you've considered**
Add a "reset" button or reset by unchecking + checking the check box to the left.

**Comment by Freymaurer** [comment]
After a quick look into the code i found that this was actually already the case. When unchecking the check box to the left Swate would remove all unit information, BUT would NOT empty the input field to the right. 

This bug will be fixed in version 0.2.1!

For now i think the most intuitive solution without convoluting the design is either removing all unit information after adding a building block or resetting it when unchecking the box to the left. Considering your argument about recycling the same unit type if needed i think we can keep the current logic (now of course bug free) of resetting the unit information when unchecking the box.
